# Generated by Django 3.2 on 2023-02-20 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_number', models.CharField(max_length=500, verbose_name='Número de série')),
                ('date_bought', models.DateField(verbose_name='Data de Compra')),
                ('status', models.CharField(max_length=100, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Bicicleta',
                'verbose_name_plural': 'Bicicletas',
            },
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ilha')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='Descrição da Ilha')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=False, quality=90, scale=None, size=[100, 150], upload_to='island')),
            ],
            options={
                'verbose_name': 'Ilha',
                'verbose_name_plural': 'Ilhas',
            },
        ),
        migrations.CreateModel(
            name='UnlockPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('hours', models.FloatField(verbose_name='Horas')),
                ('price', models.FloatField(verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bike', verbose_name='Bicicleta')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unlockpackage', verbose_name='Pacote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Compra do Utilizador',
                'verbose_name_plural': 'Compras do utilizador',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Morada')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Código Postal')),
                ('location', models.CharField(blank=True, max_length=120, null=True, verbose_name='Localização')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Número de contato')),
                ('funds', models.FloatField(blank=True, null=True, verbose_name='Fundos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
