# Generated by Django 3.2 on 2023-02-21 15:27

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bike_serie_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='description_eb',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Ilha(Inglês)'),
        ),
        migrations.AlterField(
            model_name='island',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Ilha(Português)'),
        ),
        migrations.AlterField(
            model_name='island',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=90, scale=None, size=[200, 200], upload_to='island'),
        ),
    ]
